import { useState } from "react";
import { useAppDispatch } from "../hooks";
const productsData = [
  {
    id: 1,
    name: "Ribbed modal T-shirt",
    img: "/category/cate1.png",
    discount: "10% off",
    price: "55.00",
    disc_price: "45.00",
    rating: "5.0",
    tags: "Bags, Lades bag, Fashion",
    reviews: 8,
    tag: "shirt",
    categories: ["women cloth"],
    prd_category: "Dress",
    // color: ["light pink", "blue"],
    colors: ["green", "purple", "gray", "red", "pink"],
    brand: "Abc Fashion",
    size: ["s", "l", "m", "xl", "xxl"],
    stock: "In Stock",
    createdAt: "10/12/2023",
  },
  {
    id: 2,
    name: "Loose Fit Hoodie",
    price: "50.00",
    discount: "10% off",
    disc_price: "45.00",
    rating: "5.0",
    tags: "Bags, Lades bag, Fashion",
    reviews: 0,
    tag: "shirt",
    img: "/category/cate2.png",
    categories: ["women cloth"],
    prd_category: "Sneaker",
    // color: ["blue", "light purple"],
    colors: ["green", "purple", "gray", "red", "pink"],
    brand: "Squire Style",
    size: ["s", "l", "m", "xl", "xxl"],
    stock: "In Stock",
    createdAt: "15/08/2023",
  },
  {
    id: 3,
    name: "Ribbed Tank Top",
    price: "65.00",
    disc_price: "45.00",
    discount: "10% off",
    rating: "5.0",
    tags: "Bags, Lades bag, Fashion",
    reviews: 5,
    tag: "shirt",
    img: "/category/cate3.png",
    categories: ["men cloth"],
    prd_category: "Handbag",
    // color: ["light purple", "pele"],
    colors: ["green", "purple", "gray", "red", "pink"],
    brand: "Nice Fashion",
    size: ["s", "l", "m", "xl", "xxl"],
    stock: "Out of Stock",
    createdAt: "10/11/2023",
  },
  {
    id: 4,
    name: "V-neck linen T-shirt",
    price: "55.00",
    disc_price: "45.00",
    discount: "10% off",
    rating: "5.0",
    tags: "Bags, Lades bag, Fashion",
    reviews: 10,
    tag: "shirt",
    img: "/category/cate4.png",
    categories: ["men cloth"],
    prd_category: "Cosmetics",
    // color: ["pele", "gray"],
    colors: ["green", "purple", "gray", "red", "pink"],
    brand: "Xozo Fashion",
    size: ["s", "l", "m", "xl", "xxl"],
    stock: "In Stock",
    createdAt: "10/12/2024",
  },
  {
    id: 5,
    name: "V-neck cotton T-shirt",
    price: "90.00",
    disc_price: "75.00",
    discount: "10% off",
    rating: "5.0",
    tags: "Bags, Lades bag, Fashion",
    reviews: 20,
    tag: "shirt",
    img: "/category/cate4.png",
    categories: ["men cloth"],
    prd_category: "Smart Watch",
    // color: ["gray", "jean blue", "dark blue", "red"],
    colors: ["green", "purple", "gray", "red", "pink"],
    brand: "Style Zone",
    size: ["s", "l", "m", "xl", "xxl"],
    stock: "Out of Stock",
    createdAt: "04/06/2023",
  },
  {
    id: 6,
    name: "D-neck cotton shirt",
    price: "90.00",
    disc_price: "75.00",
    discount: "10% off",
    rating: "5.0",
    tags: "Bags, Lades bag, Fashion",
    reviews: 20,
    tag: "shirt",
    img: "/category/cate4.png",
    categories: ["men cloth"],
    prd_category: "Smart Watch",
    // color: ["gray", "jean blue", "dark blue", "red"],
    colors: ["green", "purple", "gray", "red", "pink"],
    brand: "Style Zone",
    size: ["s", "l", "m", "xl", "xxl"],
    stock: "Out of Stock",
    createdAt: "04/06/2023",
  },
  {
    id: 7,
    name: "A-neck cotton T-shirt",
    price: "90.00",
    disc_price: "75.00",
    discount: "10% off",
    rating: "5.0",
    tags: "Bags, Lades bag, Fashion",
    reviews: 20,
    tag: "shirt",
    img: "/category/cate4.png",
    categories: ["men cloth"],
    prd_category: "Smart Watch",
    // color: ["gray", "jean blue", "dark blue", "red"],
    colors: ["green", "purple", "gray", "red", "pink"],
    brand: "Style Zone",
    size: ["s", "l", "m", "xl", "xxl"],
    stock: "Out of Stock",
    createdAt: "04/06/2023",
  },
  {
    id: 8,
    name: "G-neck cotton T-shirt",
    price: "90.00",
    disc_price: "75.00",
    discount: "10% off",
    rating: "5.0",
    tags: "Bags, Lades bag, Fashion",
    reviews: 20,
    tag: "shirt",
    img: "/category/cate4.png",
    categories: ["men cloth"],
    prd_category: "Smart Watch",
    // color: ["gray", "jean blue", "dark blue", "red"],
    colors: ["green", "purple", "gray", "red", "pink"],
    brand: "Style Zone",
    size: ["s", "l", "m", "xl", "xxl"],
    stock: "Out of Stock",
    createdAt: "04/06/2023",
  },

  //  for top products
  {
    id: 101,
    name: "Ribbed modal T-shirt",
    img: "/category/cate1.png",
    discount: "10% off",
    price: "45.00",
    disc_price: "35.00",
    rating: "5.0",
    tags: "Bags, Lades bag, Fashion",
    reviews: 8,
    rating: "5.0",
    tag: "shirt",
    categories: ["women cloth"],
    category: "Man",
    prd_category: "Dress",
    colors: ["green", "purple", "light brown"],
    brand: "Abs Fashion",
    size: ["XXL"],
    stock: "In Stock",
    createdAt: "10/12/2023",
  },
  {
    id: 102,
    name: "Loose Fit Hoodie",
    price: "45.00",
    discount: "10% off",
    disc_price: "25.00",
    rating: "5.0",
    tag: "shirt",
    categories: ["women cloth"],
    img: "/category/cate2.png",
    category: "Woman",
    prd_category: "Sneaker",
    colors: ["green", "purple", "light purple"],
    brand: "Squire Style",
    size: ["S"],
    stock: "In Stock",
    createdAt: "15/08/2023",
  },
  {
    id: 103,
    name: "Ribbed Tank Top",
    price: "45.00",
    disc_price: "15.00",
    discount: "10% off",
    rating: "5.0",
    tag: "shirt",
    img: "/category/cate3.png",
    categories: ["women cloth"],
    category: "New Arrival",
    prd_category: "Handbag",
    colors: ["green", "purple", "light purple", "pele"],
    brand: "Nice Fashion",
    size: ["L"],
    stock: "In Stock",
    createdAt: "10/11/2023",
  },
  {
    id: 104,
    name: "V-neck linen T-shirt",
    price: "45.00",
    disc_price: "40.00",
    discount: "10% off",
    rating: "5.0",
    tag: "shirt",
    categories: ["men cloth"],
    img: "/category/cate4.png",
    category: "Kids",
    prd_category: "Cosmetics",
    colors: ["green", "purple", "pele", "gray"],
    brand: "Xozo Fashion",
    size: ["M"],
    stock: "In Stock",
    createdAt: "10/12/2024",
  },
  {
    id: 105,
    name: "V-neck linen T-shirt",
    price: "45.00",
    disc_price: "42.00",
    discount: "10% off",
    rating: "5.0",
    tag: "shirt",
    categories: ["men cloth"],
    img: "/category/cate4.png",
    category: "Winter Collection",
    prd_category: "Smart Watch",
    colors: ["green", "purple", "gray"],
    brand: "Style Zone",
    size: ["L"],
    stock: "In stock",
    createdAt: "04/06/2023",
  },
  //trending products
  {
    id: 201,
    name: "Ribbed modal T-shirt",
    text: "Button-up shirt sleeves and a relaxed silhouette. It’s tailored with drapey, crinkle-texture fabric",
    img: "/trending/tr1.png",
    discount: "10% off",
    price: "45.00",
    disc_price: "35.00",
    rating: "5.0",
    tags: "Bags, Lades bag, Fashion",
    reviews: 8,
    rating: "5.0",
    tag: "shirt",
    categories: ["women cloth"],
    category: "Man",
    prd_category: "Dress",
    colors: ["light brown"],
    brand: "Abs Fashion",
    size: ["XXL"],
    stock: "In Stock",
    createdAt: "10/12/2023",
  },
  {
    id: 202,
    name: "Loose Fit Hoodie",
    text: "Button-up shirt sleeves and a relaxed silhouette. It’s tailored with drapey, crinkle-texture fabric",
    discount: "10% off",
    img: "/trending/tr2.png",
    price: "50.00",
    disc_price: "40.00",
    rating: "5.0",
    tags: "Bags, Lades bag, Fashion",
    reviews: 8,
    rating: "5.0",
    tag: "shirt",
    categories: ["women cloth"],
    category: "Man",
    prd_category: "Dress",
    colors: ["light brown"],
    brand: "Abs Fashion",
    size: ["XL"],
    stock: "In Stock",
    createdAt: "10/12/2023",
  },
  {
    id: 203,
    name: "Trending new hoddie",
    text: "Button-up shirt sleeves and a relaxed silhouette. It’s tailored with drapey, crinkle-texture fabric",
    discount: "10% off",
    img: "/trending/tr2.png",
    price: "60.00",
    disc_price: "30.00",
    rating: "5.0",
    tags: "Bags, Lades bag, Fashion",
    reviews: 8,
    rating: "5.0",
    tag: "shirt",
    categories: ["women cloth"],
    category: "Man",
    prd_category: "Dress",
    colors: ["light brown"],
    brand: "Abs Fashion",
    size: ["L"],
    stock: "In Stock",
    createdAt: "10/12/2023",
  },
];
export const useApi = () => {
  const [products, setProducts] = useState([]);
  const [filterData, setFilterData] = useState([]);
  const [singleProduct, setSingleProduct] = useState([]);
  const [mensProduct, setMensProduct] = useState([]);
  const [womensProduct, setWomensProduct] = useState([]);
  const dispatch = useAppDispatch();

  // const getDataFromSupabase = async () => {
  //   let data = productsData;
  //   if (data) {
  //     setProducts(data);
  //   }
  // };
  const getFilteredData = async (query) => {
    let data = productsData;
    if (data) {
      setFilterData(data);
    }
  };

  const getSingleProduct = async (id) => {
    // let {data, error} = await supabase.from('product').select('*').eq('id', id);
    // let data = productsData?.find((item) => item.id === id);
    
    if (data) {
      setSingleProduct(data);
    }
  };
  const getMensClothing = async () => {
    let data = productsData;
    if (data) {
      setMensProduct(data);
    }
  };
  const getWomensClothing = async () => {
    let data = productsData;
    if (data) {
      setWomensProduct(data);
    }
  };

  return {
    products,
    // getDataFromSupabase,
    filterData,
    getFilteredData,
    singleProduct,
    getSingleProduct,
    mensProduct,
    getMensClothing,
    womensProduct,
    getWomensClothing,
  };
};
